package io.github.probably_oxy.drift.ui

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.LocalUriHandler
import androidx.compose.ui.text.font.FontStyle
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import io.github.probably_oxy.drift.data.Catalogue
import io.github.probably_oxy.drift.data.License
import io.github.probably_oxy.drift.data.Sound
import io.github.probably_oxy.drift.ui.theme.JetBrainsMono
import io.github.probably_oxy.drift.ui.theme.LocalDriftColors

/**
 * About body — offline/no-tracking blurb + runtime version. Rendered inside the menu
 * drawer's About sub-view (the drawer supplies the title/back chrome).
 */
@Composable
fun AboutContent() {
    val colors = LocalDriftColors.current
    val context = LocalContext.current
    val version = remember(context) {
        runCatching {
            context.packageManager.getPackageInfo(context.packageName, 0).versionName
        }.getOrNull() ?: "—"
    }
    Column {
        Text(
            text = "Ambient soundscape player for Android.\n" +
                "All sounds play fully offline.\n" +
                "No tracking. No data collected.",
            color = colors.textDim,
            fontFamily = JetBrainsMono,
            fontSize = 13.sp,
            lineHeight = 26.sp,
            letterSpacing = 0.7.sp,
        )
        Spacer(Modifier.height(28.dp))
        Text(
            text = "VERSION $version",
            color = colors.greenFaint,
            fontFamily = JetBrainsMono,
            fontSize = 9.sp,
            letterSpacing = 2.sp,
        )
    }
}

/**
 * Credits body — generated from the catalogue so it never drifts from the real audio
 * set. Rendered inside the menu drawer's Credits sub-view.
 */
@Composable
fun CreditsContent() {
    val colors = LocalDriftColors.current
    Column {
        val byLicense = Catalogue.sounds.groupBy { it.license.license }
        val order = listOf(
            License.CC0 to "FIELD RECORDINGS · CC0",
            License.PUBLIC_DOMAIN to "SPACE RECORDINGS · PUBLIC DOMAIN",
            License.CC_BY_3_0 to "CC BY 3.0",
            License.CC_BY_4_0 to "CC BY 4.0",
        )
        order.forEach { (license, heading) ->
            val sounds = byLicense[license].orEmpty()
            if (sounds.isNotEmpty()) {
                CreditSection(heading) { sounds.forEach { SoundCredit(it) } }
            }
        }

        byLicense[License.ORIGINAL]?.let { original ->
            CreditSection("ORIGINAL / SYNTHESISED") {
                Text(
                    text = original.joinToString(", ") { it.name },
                    color = colors.greenFaint,
                    fontFamily = JetBrainsMono,
                    fontSize = 12.sp,
                    fontStyle = FontStyle.Italic,
                )
                Spacer(Modifier.height(4.dp))
                Text(
                    text = "Generated by Drift. No audio data is transmitted.",
                    color = colors.greenFaint,
                    fontFamily = JetBrainsMono,
                    fontSize = 10.sp,
                )
            }
        }

        CreditSection("TYPEFACE") {
            Text("JetBrains Mono", color = colors.textDim, fontFamily = JetBrainsMono, fontSize = 13.sp, fontStyle = FontStyle.Italic)
            Spacer(Modifier.height(4.dp))
            Text("JetBrains · SIL Open Font License 1.1", color = colors.greenFaint, fontFamily = JetBrainsMono, fontSize = 11.sp)
            LinkText("github.com/JetBrains/JetBrainsMono", "https://github.com/JetBrains/JetBrainsMono")
        }

        Spacer(Modifier.height(20.dp))
        Text(
            text = "Drift — all sounds play offline · no tracking",
            color = colors.greenFaint,
            fontFamily = JetBrainsMono,
            fontSize = 9.sp,
            letterSpacing = 1.5.sp,
            modifier = Modifier.fillMaxWidth(),
        )
    }
}

@Composable
private fun SoundCredit(sound: Sound) {
    val colors = LocalDriftColors.current
    val info = sound.license
    Column(Modifier.fillMaxWidth().padding(bottom = 12.dp)) {
        Row(verticalAlignment = Alignment.CenterVertically) {
            Text(
                text = sound.name,
                color = colors.textDim,
                fontFamily = JetBrainsMono,
                fontSize = 13.sp,
                fontStyle = FontStyle.Italic,
                modifier = Modifier.weight(1f),
            )
            Text(text = licenseLabel(info.license), color = colors.greenFaint, fontFamily = JetBrainsMono, fontSize = 9.sp)
        }
        info.author?.let {
            Text(text = it, color = colors.greenFaint, fontFamily = JetBrainsMono, fontSize = 11.sp)
        }
        info.url?.let { LinkText(it.removePrefix("https://").removePrefix("http://").take(60), it) }
    }
}

@Composable
private fun LinkText(label: String, url: String) {
    val colors = LocalDriftColors.current
    val uriHandler = LocalUriHandler.current
    Text(
        text = label,
        color = colors.greenDim,
        fontFamily = JetBrainsMono,
        fontSize = 9.sp,
        modifier = Modifier
            .padding(top = 4.dp)
            .clickable { runCatching { uriHandler.openUri(url) } },
    )
}

private fun licenseLabel(license: License): String = when (license) {
    License.CC0 -> "CC0"
    License.PUBLIC_DOMAIN -> "Public Domain"
    License.CC_BY_3_0 -> "CC BY 3.0"
    License.CC_BY_4_0 -> "CC BY 4.0"
    License.ORIGINAL -> "Original"
}

@Composable
private fun CreditSection(heading: String, content: @Composable () -> Unit) {
    val colors = LocalDriftColors.current
    Text(text = heading, color = colors.greenDim, fontFamily = JetBrainsMono, fontSize = 10.sp, letterSpacing = 3.sp)
    Spacer(Modifier.height(10.dp))
    Column(
        Modifier
            .fillMaxWidth()
            .clip(RoundedCornerShape(9.dp))
            .background(colors.cardBg)
            .border(1.dp, colors.cardLine, RoundedCornerShape(9.dp))
            .padding(14.dp),
    ) { content() }
    Spacer(Modifier.height(18.dp))
}
