package io.github.probably_oxy.drift.ui

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.LocalUriHandler
import androidx.compose.ui.text.font.FontStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import io.github.probably_oxy.drift.data.Catalogue
import io.github.probably_oxy.drift.data.License
import io.github.probably_oxy.drift.data.Sound
import io.github.probably_oxy.drift.ui.theme.Bg
import io.github.probably_oxy.drift.ui.theme.BorderPanel
import io.github.probably_oxy.drift.ui.theme.Surface
import io.github.probably_oxy.drift.ui.theme.TextBadge
import io.github.probably_oxy.drift.ui.theme.TextDim
import io.github.probably_oxy.drift.ui.theme.TextEyebrow
import io.github.probably_oxy.drift.ui.theme.TextFooter
import io.github.probably_oxy.drift.ui.theme.TextMuted
import io.github.probably_oxy.drift.ui.theme.TextPrimary
import io.github.probably_oxy.drift.ui.theme.TextSection

/** Full-screen "About" overlay. */
@Composable
fun AboutScreen(onClose: () -> Unit) {
    val context = LocalContext.current
    val version = remember(context) {
        runCatching {
            context.packageManager.getPackageInfo(context.packageName, 0).versionName
        }.getOrNull() ?: "—"
    }

    InfoScaffold(title = "DRIFT // AUDIO", onClose = onClose) {
        Text(
            text = "Ambient soundscape player for Android.\n" +
                "All sounds play fully offline.\n" +
                "No tracking. No data collected.",
            color = TextDim,
            fontSize = 13.sp,
            lineHeight = 26.sp,
            letterSpacing = 0.7.sp,
        )
        Spacer(Modifier.height(28.dp))
        Text(
            text = "VERSION $version",
            color = TextFooter,
            fontSize = 9.sp,
            letterSpacing = 2.sp,
        )
    }
}

/** Full-screen "Credits" overlay — generated from the catalogue, so it never drifts. */
@Composable
fun CreditsScreen(onClose: () -> Unit) {
    InfoScaffold(title = "CREDITS", onClose = onClose) {
        // Group sounds with real attribution by licence; ORIGINAL/SYN handled below.
        val byLicense = Catalogue.sounds.groupBy { it.license.license }
        val order = listOf(
            License.CC0 to "FIELD RECORDINGS · CC0",
            License.PUBLIC_DOMAIN to "SPACE RECORDINGS · PUBLIC DOMAIN",
            License.CC_BY_3_0 to "CC BY 3.0",
            License.CC_BY_4_0 to "CC BY 4.0",
        )
        order.forEach { (license, heading) ->
            val sounds = byLicense[license].orEmpty()
            if (sounds.isNotEmpty()) {
                CreditSection(heading) { sounds.forEach { SoundCredit(it) } }
            }
        }

        byLicense[License.ORIGINAL]?.let { original ->
            CreditSection("ORIGINAL / SYNTHESISED") {
                Text(
                    text = original.joinToString(", ") { it.name },
                    color = TextMuted,
                    fontSize = 12.sp,
                    fontStyle = FontStyle.Italic,
                )
                Spacer(Modifier.height(4.dp))
                Text(
                    text = "Generated by Drift. No audio data is transmitted.",
                    color = TextFooter,
                    fontSize = 10.sp,
                )
            }
        }

        CreditSection("TYPEFACE") {
            Text("JetBrains Mono", color = TextDim, fontSize = 13.sp, fontStyle = FontStyle.Italic)
            Spacer(Modifier.height(4.dp))
            Text("JetBrains · SIL Open Font License 1.1", color = TextMuted, fontSize = 11.sp)
            LinkText("github.com/JetBrains/JetBrainsMono", "https://github.com/JetBrains/JetBrainsMono")
        }

        Spacer(Modifier.height(20.dp))
        Text(
            text = "Drift — all sounds play offline · no tracking",
            color = TextFooter,
            fontSize = 9.sp,
            letterSpacing = 1.5.sp,
            modifier = Modifier.fillMaxWidth(),
        )
    }
}

@Composable
private fun SoundCredit(sound: Sound) {
    val info = sound.license
    Column(Modifier.fillMaxWidth().padding(bottom = 12.dp)) {
        Row(verticalAlignment = Alignment.CenterVertically) {
            Text(
                text = sound.name,
                color = TextDim,
                fontSize = 13.sp,
                fontStyle = FontStyle.Italic,
                modifier = Modifier.weight(1f),
            )
            Text(text = licenseLabel(info.license), color = TextBadge, fontSize = 9.sp)
        }
        info.author?.let {
            Text(text = it, color = TextMuted, fontSize = 11.sp)
        }
        info.url?.let { LinkText(it.removePrefix("https://").removePrefix("http://").take(60), it) }
    }
}

@Composable
private fun LinkText(label: String, url: String) {
    val uriHandler = LocalUriHandler.current
    Text(
        text = label,
        color = TextEyebrow,
        fontSize = 9.sp,
        modifier = Modifier
            .padding(top = 4.dp)
            .clickable { runCatching { uriHandler.openUri(url) } },
    )
}

private fun licenseLabel(license: License): String = when (license) {
    License.CC0 -> "CC0"
    License.PUBLIC_DOMAIN -> "Public Domain"
    License.CC_BY_3_0 -> "CC BY 3.0"
    License.CC_BY_4_0 -> "CC BY 4.0"
    License.ORIGINAL -> "Original"
}

@Composable
private fun CreditSection(heading: String, content: @Composable () -> Unit) {
    Text(text = heading, color = TextSection, fontSize = 10.sp, letterSpacing = 3.sp)
    Spacer(Modifier.height(10.dp))
    Column(
        Modifier
            .fillMaxWidth()
            .clip(RoundedCornerShape(10.dp))
            .background(Surface)
            .border(1.dp, BorderPanel, RoundedCornerShape(10.dp))
            .padding(14.dp),
    ) { content() }
    Spacer(Modifier.height(18.dp))
}

/** Shared chrome: dark full-screen surface, title row with a ✕, scrolling body. */
@Composable
private fun InfoScaffold(
    title: String,
    onClose: () -> Unit,
    body: @Composable () -> Unit,
) {
    Column(
        Modifier
            .fillMaxSize()
            .background(Bg)
            .verticalScroll(rememberScrollState())
            .padding(horizontal = 20.dp, vertical = 24.dp),
    ) {
        Row(
            modifier = Modifier.fillMaxWidth().padding(bottom = 20.dp),
            verticalAlignment = Alignment.CenterVertically,
        ) {
            Text(
                text = title,
                color = TextPrimary,
                fontSize = 15.sp,
                fontWeight = FontWeight.Bold,
                letterSpacing = 3.sp,
                modifier = Modifier.weight(1f),
            )
            Text(
                text = "✕",
                color = TextMuted,
                fontSize = 20.sp,
                modifier = Modifier.clickable(onClick = onClose).padding(8.dp),
            )
        }
        body()
    }
}
